# Generated by Django 4.2.6 on 2023-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='image',
            new_name='src',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
