# Generated by Django 4.2.6 on 2023-12-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_specification_item_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.catalog', verbose_name='каталог'),
        ),
    ]
