# Generated by Django 4.2.6 on 2023-12-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='products',
        ),
    ]
