# Generated by Django 4.2.6 on 2023-11-23 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=5000)),
                ('rate', models.SmallIntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.product', verbose_name='продукт')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
