# Generated by Django 4.2.6 on 2023-11-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='item_image',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='specification',
        ),
        migrations.AddField(
            model_name='specification',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='specifications', to='backend.item'),
        ),
        migrations.AddField(
            model_name='tag',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='backend.item'),
        ),
    ]
