# Generated by Django 4.2.6 on 2023-12-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_image_itemimage_src_itemimage_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='specification',
            new_name='specifications',
        ),
    ]
