# Generated by Django 4.2.6 on 2023-11-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_item_image_itemimage_item_remove_item_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='item',
        ),
        migrations.AddField(
            model_name='tag',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='tags', to='backend.item'),
        ),
    ]
