# Generated by Django 4.2.6 on 2023-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_review_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='silePrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
