# Generated by Django 4.2.6 on 2023-12-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_catalog_options_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id', 'rating', 'price', 'reviews', 'date']},
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='backend.item')),
            ],
            bases=('backend.item',),
        ),
    ]
