# Generated by Django 4.2.6 on 2023-12-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_item_active_item_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='backend.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='filter',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='catalog',
            name='limit',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='catalog',
            name='sort',
            field=models.CharField(choices=[('rating', 'rating'), ('price', 'price'), ('reviews', 'reviews'), ('date', 'date')], default='date', max_length=9),
        ),
        migrations.AddField(
            model_name='catalog',
            name='sortType',
            field=models.CharField(choices=[('dec', 'dec'), ('inc', 'inc')], default='dec', max_length=9),
        ),
        migrations.AddField(
            model_name='tag',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='backend.catalog', verbose_name='каталог'),
            preserve_default=False,
        ),
    ]
