# Generated by Django 4.2.6 on 2023-12-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_catalog_category_catalog_filter_catalog_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='silePrice',
            new_name='salePrice',
        ),
    ]
