# Generated by Django 4.2.6 on 2023-12-24 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_profile_options_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deliveryType', models.CharField(choices=[('free', 'Бесплатная доставка'), ('paid', 'Платная доставка')], default='Тип доставки', max_length=9)),
                ('paymentType', models.CharField(choices=[('online', 'Онлайн картой'), ('online_any', 'Онлайн оплата со случайного счета')], default='Тип оплаты', max_length=20)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('awaiting payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('in transit', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('basket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.basket')),
                ('items', models.ManyToManyField(related_name='products', to='backend.item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
