# Generated by Django 4.2.6 on 2023-12-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_items_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=3)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.order')),
            ],
        ),
    ]
